name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t my_docker .
      
  tests:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - name: Run experiments
      run: |
        docker run -it my_docker
        source sourceme.sh
        10
        cd dory
        python3 -m pytest
